# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-22 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dn_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
